name: pizza_repository
description: The Repo that handles pizzas
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.8
  flutter:
    sdk: flutter
  version: ^3.0.2
dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
